### ISSUE TITLE
Missing GitChecker example

### ISSUE THREAD

**Issue by jreina** [jonathanfmills/TestingNodeWithMocha#2]
In module 6 of the PluralSight course you show a working example and mention that GitChecker should be available in this repo. Is that supposed to be in this repository? Perhaps I just missed something.

**Comment by i0na-k** [comment]
Yeah I agree - where is it?

**Comment by fakefarm** [comment]
I'm here for the same thing 👀

**Comment by jonathanfmills** [comment]
Sorry everyone, It is out there now.

**Comment by jreina** [comment]
Thank you sir! That will be quite helpful.
