### ISSUE TITLE
Module 3-5 Testing Something Real

### ISSUE THREAD

**Issue by trebleCode** [jonathanfmills/TestingNodeWithMocha#3]
Hi Jonathan,

In attempting to follow along (albeit on Windows *cringe*), I cloned this repo to use as a guide.

Steps:
- Setup nvm-windows and using v7.9.0
- Install npm in the directory
- npm i -g mocha@3.2.0
- npm i mocha@3.2.0
- Follow your tutorial's steps for creating a controllers folder, etc etc

This much code:
```
var assert = require('assert');
var authController = require('../../controllers/auth.controller');

describe('AuthController', function () {
    describe('isAuthorized', function () {
        it('Should return false if not authorized', function () {
            assert.equal(false, authController.isAuthorized(['user'], 'admin'));
        })
    })
});
```

returns the following output after 
[someConsole]>mocha "./test/**/*.spec.js"

```
  AuthController
    isAuthorized
      1) Should return false if not authorized

  Basic Mocha Test
    √ should throw errors


  1 passing (15ms)
  1 failing

  1) AuthController isAuthorized Should return false if not authorized:
     AssertionError: false == -1
      at Context.<anonymous> (test\controllers\auth.controller.spec.js:7:20)
```

when based on the demonstrated example in the tutorial it should technically pass

Can you provide some advice?

**Comment by jonathanfmills** [comment]
Hey, Sorry for the delay, I have been traveling. Did you get this figured out?

**Comment by trebleCode** [comment]
Hey Jonathan,

Yes I was was, that's why I closed it. Thanks for the response regardless, and happy weekend
